name: "Download K3S images"
description: "Download k3s images txt file and save airgap images"
inputs:
  k3s_version:
    description: "k3s version"
    required: true
runs:
  using: "composite"
  steps:
    - name: Download images txt file
      shell: bash
      run: curl -sLf https://github.com/rancher/k3s/releases/download/${{ inputs.k3s_version }}/k3s-images.txt -o ${{ runner.temp }}/k3s-images.txt
    - name: Create k3s images file
      shell: bash
      run: |
        if [ -e ${{ runner.temp }}/k3s-images.txt ]; then
            images=$(grep -e 'docker.io/rancher/mirrored-pause' -e 'docker.io/rancher/mirrored-coredns-coredns' ${{ runner.temp }}/k3s-images.txt)
            xargs -n1 docker pull <<< "${images}"
            docker save -o ./k3s-airgap-images.tar ${images}
        else
            touch k3s-airgap-images.tar
        fi
