name: Running Test Script
on:
  workflow_dispatch:

jobs:
  test-script:
    name: Running test script
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: script
        run: |
          ./scripts/test
        shell: bash
