name: Running Test Script
on:
  workflow_dispatch:

jobs:
  test-script:
    name: Running test script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #- name: Script Part 1
        #run: |
          #./scripts/test_0
        #shell: bash

      - name: Script Part 2
        run: |
          ./scripts/test_1
        shell: bash
