name: default-linux-amd64
on: [pull_request]
jobs:
  build-pr:
    runs-on: org-${{ github.repository_owner_id }}-amd64-k8s
    container: 
      image: rancher/dapper:v0.6.0
      options: --user root --privileged
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Add Git
        run: apk add -U git
      - name: Add Docker
        run: apk add -U docker 
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Validate
        run: dapper validate
      - name: Build Rancher
        run: dapper ci
