name: default-linux-amd64
on: [pull_request]
jobs:
  build-pr:
    runs-on: org-${{ github.repository_owner_id }}-amd64-k8s
    container: 
      image: docker:dind
      options: --privileged
    steps:
      - name: Install dependencies
        run: apk update; apk add curl; apk add git
      - name: Add Dapper
        run: |
          curl -sL https://releases.rancher.com/dapper/latest/dapper-$(uname -s)-$(uname -m) > /usr/local/bin/dapper
          chmod +x /usr/local/bin/dapper
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Validate
        run: dapper validate
      - name: Build Rancher
        run: /usr/local/bin/dapper ci
