name: default-linux-amd64
on: [pull_request]
jobs:
  build-pr:
    runs-on: org-${{ github.repository_owner_id }}-amd64-k8s
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Validate
        run: ./scripts/validate
      - name: Build Rancher
        run: ./scripts/ci
