name: Running Test Script
on:
  workflow_dispatch:

jobs:
  build-server:
    name: Build rancher server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Build Server
        run: |
          ./scripts/build-server
        shell: bash

      - name: Upload Rancher Binary
        uses: actions/upload-artifact@v4
        with:
          name: rancher
          path: bin/rancher

  integration-testing:
    name: Integration tests
    runs-on: ubuntu-latest
    needs:
      - build-server
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Rancher Binary
        uses: actions/download-artifact@v4
        with:
          name: rancher
          path: bin

      - name: Make Rancher Binary Executable
        run: chmod +x ./bin/rancher
        shell: bash

      - name: Install K3s
        run: curl -sfL https://get.k3s.io | sh - 
        shell: bash

      - name: Start k3s
        run: |
          sudo systemctl start k3s
          sudo systemctl status k3s
          sudo journalctl -u k3s
        shell: bash

      - name: Integration tests
        run: |
          ./scripts/integration-test
        shell: bash

  #unit-testing:
    #name: Unit tests
    #runs-on: ubuntu-latest
    #steps:
      #- name: Checkout code
        #uses: actions/checkout@v4

      #- name: Unit testing
        #run: |
          #./scripts/unit-test
        #shell: bash

      #- name: Integration tests
        #run: |
          #./scripts/integration-test
        #shell: bash

      #- name: Change permissions on /var/lib/rancher
        #run: |
          #sudo mkdir -p /var/lib/rancher
          #sudo chown $USER:$USER /var/lib/rancher
        #shell: bash

      #- name: Script Part 2
        #run: |
          #./scripts/test_1
        #shell: bash
