name: Promote version to stable
on: 
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: "e.g: v2.8.4"
        required: true
env:
  REGISTRY: "docker.io"
  IMAGE: ${{ github.repository }}
  TAG: ${{ github.event.inputs.tag }}
  GIT_TAG: ${{ github.event.inputs.tag }}
jobs:
  update-readme:
    needs: [promote-docker-image]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Update readme to new stable
        shell: bash
        run: |
          # get the current stable from the README comment
          STABLE_VERSION=$(grep -m1 '<!-- stable' README.md | cut -d ' ' -f3)
          # replace the current stable with the new stable
          sed -i "s/$STABLE_VERSION/$TAG/g" README.md
          # get only the minor version e.g. v2.11 and replace with the new minor
          STABLE_MINOR=$(echo "$STABLE_VERSION" | cut -d '.' -f1,2)
          NEW_STABLE_MINOR=$(echo "$TAG" | cut -d '.' -f1,2)
          sed -i "s/$STABLE_MINOR/$NEW_STABLE_MINOR/g" README.md
      - name: Create PR
        shell: bash
        run: |
          BRANCH="githubaction-update-readme-$(date +%Y-%m-%d-%H-%M-%S)"
          echo "BRANCH=$BRANCH" >> $GITHUB_EN
          echo "::set-output name=branch::$BRANCH"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout -b "$BRANCH"
          git commit -a -m "update README with latest/stable"
          git push origin "$BRANCH"
      - name: Create PR
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "update README with latest/stable" \
            --body "Auto-generated by GitHub Actions" \
            --base "main" \
            --head "$BRANCH" \
            --assignee ${{ github.triggering_actor }}
