name: Promote version to stable
on: 
  workflow_dispatch:
jobs:
  install-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: setup ecm-distro-tools
        uses: tashima42/ecm-distro-tools@0ac21a6e9ec660b9715dfeed21eda60f4abfab20
      - shell: bash
        run: release -v
  install-bci:
    runs-on: ubuntu-latest
    container: registry.suse.com/bci/bci-base:latest
    steps:
      - name: setup ecm-distro-tools
        uses: tashima42/ecm-distro-tools@0ac21a6e9ec660b9715dfeed21eda60f4abfab20
