name: Build Head Images
on: 
  push:
    branches:
      - "main"
      - "release/v*"
env:
  COMMIT: ${{ github.sha }}
  REPOSITORY_OWNER: ${{ github.repository_owner }}
  IMAGE: ${{ github.repository_owner }}/rancher
  IMAGE_AGENT: ${{ github.repository_owner }}/rancher-agent
  IMAGE_INSTALLER: ${{ github.repository_owner }}/system-agent-installer-rancher
  REGISTRY: "docker.io"
  GH_CLI_VERSION: 2.66.0
jobs:
  unit-tests:
    uses: ./.github/workflows/unit-test.yml
  build-server:
    uses: ./.github/workflows/build-server.yml
  build-agent:
    uses: ./.github/workflows/build-agent.yml
  integration-tests:
    needs: [build-agent]
    uses: ./.github/workflows/integration-tests.yml
    with:
      parent_run_id: ${{ github.run_id }}
