name: Release
on: 
  tags:
    - "v*"
env:
  COMMIT: ${{ github.sha }}
  REPOSITORY_OWNER: ${{ github.repository_owner }}
  IMAGE: ${{ github.repository_owner }}/rancher
  IMAGE_AGENT: ${{ github.repository_owner }}/rancher-agent
  IMAGE_INSTALLER: ${{ github.repository_owner }}/system-agent-installer-rancher
  REGISTRY: "docker.io"
  GH_CLI_VERSION: 2.66.0
jobs:
  unit-tests:
    uses: ./.github/workflows/unit-test.yml
  build-server:
    uses: ./.github/workflows/release/build-server.yml
  build-agent:
    uses: ./.github/workflows/release/build-agent.yml
  integration-tests:
    needs: [build-agent]
    uses: ./.github/workflows/integration-tests.yml
  build-agent-windows:
    needs: [integration-tests]
    uses: ./.github/workflows/release/build-agent-windows.yml
  push-images:
    needs: [unit-tests, integration-tests]
    uses: ./.github/workflows/release/push-images.yml
  merge-server-manifest:
    needs: [push-images]
    uses: ./.github/workflows/release/merge-server-manifest.yml
  merge-agent-manifest:
    needs: [push-images, build-agent-windows]
    uses: ./.github/workflows/release/merge-agent-manifest.yml
  build-publish-chart:
    runs-on: org-${{ github.repository_owner_id }}-amd64-k8s
    container: registry.suse.com/bci/bci-base:latest
    needs: [push-images]
    permissions:
      contents: read
      id-token: write
    env:
      ARCH: amd64
    steps:
      - name: Build
        uses: ./.github/actions/charts/build
      - name: Upload
        uses: ./.github/actions/charts/upload
  images-files:
    runs-on: runs-on,runner=2cpu-linux-x64,image=ubuntu22-full-x64,run-id=${{ github.run_id }}
    permissions:
      contents: write
      id-token: write
    env:
      REGISTRY: ""
      CHECKSUM_FILE: "sha256sum.txt"
      ARTIFACTS_BASE_DIR: "bin"
    steps:
      - name: Generate
        uses: ./.github/actions/images-files/generate
      - name: Upload
        uses: ./.github/actions/images-files/upload
