name: Print Run ID
on:
  workflow_call:
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Run ID
        shell: bash
        run: echo "hello, this should run on all runs ${{ github.run_id }}"
